package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Street")
   private java.lang.String street;
   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "Province")
   private java.lang.String province;
   @org.kie.api.definition.type.Label(value = "Postal Code")
   private java.lang.String postalCode;

   public Address()
   {
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getProvince()
   {
      return this.province;
   }

   public void setProvince(java.lang.String province)
   {
      this.province = province;
   }

   public java.lang.String getPostalCode()
   {
      return this.postalCode;
   }

   public void setPostalCode(java.lang.String postalCode)
   {
      this.postalCode = postalCode;
   }

   public Address(java.lang.String street, java.lang.String city,
         java.lang.String province, java.lang.String postalCode)
   {
      this.street = street;
      this.city = city;
      this.province = province;
      this.postalCode = postalCode;
   }

}