package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Drug implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "DIN")
   private java.lang.String din;
   @org.kie.api.definition.type.Label(value = "Name od Drug")
   private java.lang.String name;

   public Drug()
   {
   }

   public java.lang.String getDin()
   {
      return this.din;
   }

   public void setDin(java.lang.String din)
   {
      this.din = din;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Drug(java.lang.String din, java.lang.String name)
   {
      this.din = din;
      this.name = name;
   }

}