package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DrugCurrentHistory implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DrugCurrentHistory() {
    }

}