package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DrugCurrentHistory implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "List of Drug")
   private java.util.List<com.redhat.demos.unlisteddrugrequest.Drug> drugList;

   public DrugCurrentHistory()
   {
   }

   public java.util.List<com.redhat.demos.unlisteddrugrequest.Drug> getDrugList()
   {
      return this.drugList;
   }

   public void setDrugList(
         java.util.List<com.redhat.demos.unlisteddrugrequest.Drug> drugList)
   {
      this.drugList = drugList;
   }

   public DrugCurrentHistory(
         java.util.List<com.redhat.demos.unlisteddrugrequest.Drug> drugList)
   {
      this.drugList = drugList;
   }

}