package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DrugRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "DIN")
   private java.lang.String din;
   @org.kie.api.definition.type.Label(value = "Start Date")
   private java.lang.String startDate;

   public DrugRequest()
   {
   }

   public java.lang.String getDin()
   {
      return this.din;
   }

   public void setDin(java.lang.String din)
   {
      this.din = din;
   }

   public java.lang.String getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.lang.String startDate)
   {
      this.startDate = startDate;
   }

   public DrugRequest(java.lang.String din, java.lang.String startDate)
   {
      this.din = din;
      this.startDate = startDate;
   }

}