package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Drug implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("DIN")
   @org.kie.api.definition.type.Description("Drug Identification Number")
   private java.lang.String din;
   @org.kie.api.definition.type.Label("Name of Drug")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Current?")
   private boolean current;

   @org.kie.api.definition.type.Label("Dosage")
   private java.lang.String dosage;

   @org.kie.api.definition.type.Label("Alternatives Inappropriate Reason")
   @org.kie.api.definition.type.Description("Reason(s) why formulary alternatives are not appropriate")
   private java.lang.String alternativesInappropriateReason;

   @org.kie.api.definition.type.Label(value = "Therapy Duration")
   private java.lang.String therapyDuration;

   public Drug()
   {
   }

   public java.lang.String getDin()
   {
      return this.din;
   }

   public void setDin(java.lang.String din)
   {
      this.din = din;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public boolean isCurrent()
   {
      return this.current;
   }

   public void setCurrent(boolean current)
   {
      this.current = current;
   }

   public java.lang.String getDosage()
   {
      return this.dosage;
   }

   public void setDosage(java.lang.String dosage)
   {
      this.dosage = dosage;
   }

   public java.lang.String getAlternativesInappropriateReason()
   {
      return this.alternativesInappropriateReason;
   }

   public void setAlternativesInappropriateReason(
         java.lang.String alternativesInappropriateReason)
   {
      this.alternativesInappropriateReason = alternativesInappropriateReason;
   }

   public java.lang.String getTherapyDuration()
   {
      return this.therapyDuration;
   }

   public void setTherapyDuration(java.lang.String therapyDuration)
   {
      this.therapyDuration = therapyDuration;
   }

   public Drug(java.lang.String din, java.lang.String name, boolean current,
         java.lang.String dosage,
         java.lang.String alternativesInappropriateReason,
         java.lang.String therapyDuration)
   {
      this.din = din;
      this.name = name;
      this.current = current;
      this.dosage = dosage;
      this.alternativesInappropriateReason = alternativesInappropriateReason;
      this.therapyDuration = therapyDuration;
   }

}