package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "First Name")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "Last Name")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;

   public Patient()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public Patient(java.lang.String firstName, java.lang.String lastName,
         java.lang.Integer age)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.age = age;
   }

}