package com.redhat.demos.unlisteddrugrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Physician implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Physician ID")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Full Name")
   private java.lang.String fullName;

   public Physician()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getFullName()
   {
      return this.fullName;
   }

   public void setFullName(java.lang.String fullName)
   {
      this.fullName = fullName;
   }

   public Physician(java.lang.String id, java.lang.String fullName)
   {
      this.id = id;
      this.fullName = fullName;
   }

}